name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    
    env:
      CI: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting and formatting checks
      run: npm run fix

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: matrix.node-version == 20
      with:
        name: coverage-reports
        path: coverage/

    - name: Build project
      run: npm run build

    - name: Verify build output
      run: |
        if [ ! -f dist/bin/index.js ]; then
          echo "Build output not found!"
          exit 1
        fi
        echo "Build successful!"